F:  # Faraday's constant
  value: 9.649e4
  unit: coulomb/mole
qe:  # elementary charge
  value: 1.6e-19
  unit: coulomb
R:  # gas constant
  value: 8.314
  unit: joule/kelvin/mole
kB:  # Boltzmann constant
  value: 1.381e-23
  unit: joule/kelvin
T:  # standard temperature
  value: 298.15
  unit: kelvin
zCa:  # Ca2+ valence
  value: 2
  unit:
zK:  # K+ valence
  value: 1
  unit:
DCa:  # diffusion coefficient for free-Ca2+ in water
  value: 800
  unit: micrometer**2/second
gamma:  # geometric factor for hair bundle position
  value: 0.14
  unit:

# Ca2+ concentration at soma
U:  # proportion of free calcium
  value: 0.02
  unit:
xiCa:  # volumetric proportion of calcium near membrane
  value: 3.4e-5
  unit:
Cvol:  # cell volume
  value: 1.25
  unit: picoliter
KS:  # rate constant
  value: 2.8
  unit: kilohertz

# Ca2+ channel at soma
tauinfCa:
  value: 0.046
  unit: millisecond
tauVtauCa:
  value: 0.371
  unit: millisecond
VtauCa:
  value: -77
  unit: millivolt
dVtauCa:
  value: 51.67
  unit: millivolt
dVCa:
  value: 12.2
  unit: millivolt
VhalfCa:
  value: -55
  unit: millivolt
mhmaxCa:
  value: 1
  unit:
mhminCa:
  value: 0
  unit:
deltaCa:
  value: 1
  unit:
deltatauCa:
  value: 2
  unit:

# fast K1 channel
aK1f:
  value: 0.7
  unit:
tauinfK1fgt:  # Vm>=E_{K1f}
  value: 0.04
  unit: millisecond
tauVtauK1fgt:  # Vm>=E_{K1f}
  value: 0.74
  unit: millisecond
VtauK1fgt:  # Vm>=E_{K1f}
  value: -120
  unit: millivolt
dVtauK1fgt:  # Vm>=E_{K1f}
  value: 43.8
  unit: millivolt
tauinfK1flt:  # Vm<E_{K1f}
  value: 0.17
  unit: millisecond
tauVtauK1flt:  # Vm<E_{K1f}
  value: 7.67
  unit: millisecond
VtauK1flt:  # Vm<E_{K1f}
  value: -80
  unit: millivolt
dVtauK1flt:  # Vm<E_{K1f}
  value: -30.5
  unit: millivolt
dVK1f:
  value: -11
  unit: millivolt
VhalfK1f:
  value: -110
  unit: millivolt
mhmaxK1f:
  value: 1
  unit:
mhminK1f:
  value: 0
  unit:
deltaK1f:
  value: 1
  unit:
deltatauK1f:
  value: 1
  unit:

# slow K1 channel
tauinfK1sgt:  # Vm>=E_{K1s}
  value: 0.04
  unit: millisecond
tauVtauK1sgt:  # Vm>=E_{K1s}
  value: 14.14
  unit: millisecond
VtauK1sgt:  # Vm>=E_{K1s}
  value: -120
  unit: millivolt
dVtauK1sgt:  # Vm>=E_{K1s}
  value: 28
  unit: millivolt
tauinfK1slt:  # Vm<E_{K1s}
  value: 0.17
  unit: millisecond
tauVtauK1slt:  # Vm<E_{K1s}
  value: 7.67
  unit: millisecond
VtauK1slt:  # Vm<E_{K1s}
  value: -80
  unit: millivolt
dVtauK1slt:  # Vm<E_{K1s}
  value: -30.5
  unit: millivolt
dVK1s:
  value: -11
  unit: millivolt
VhalfK1s:
  value: -110
  unit: millivolt
mhmaxK1s:
  value: 1
  unit:
mhminK1s:
  value: 0
  unit:
deltaK1s:
  value: 1
  unit:
deltatauK1s:
  value: 1
  unit:

# h channel
tauinfh:
  value: 63.7
  unit: millisecond
tauVtauh:
  value: 199.4
  unit: millisecond
Vtauh:
  value: -91.4
  unit: millivolt
dVtauh:
  value: 21.2
  unit: millivolt
dVh:
  value: -16.7
  unit: millivolt
Vhalfh:
  value: -87
  unit: millivolt
mhmaxh:
  value: 1
  unit:
mhminh:
  value: 0
  unit:
deltah:
  value: 1
  unit:
deltatauh:
  value: 2
  unit:

# BKT channel
tauinfBKT:
  value: 2.1
  unit: millisecond
tauVtauBKT:
  value: 11.5
  unit: millisecond
VtauBKT:
  value: 66.9
  unit: millivolt
dVtauBKT:
  value: 17.7
  unit: millivolt
dVBKT:
  value: -3.65
  unit: millivolt
VhalfBKT:
  value: -61.6
  unit: millivolt
mhmaxBKT:
  value: 1
  unit:
mhminBKT:
  value: 0
  unit:
deltaBKT:
  value: 1
  unit:
deltatauBKT:
  value: 2
  unit:

# DRK channel
alphainf:
  value: 333
  unit: hertz
alpha0:
  value: 161
  unit: hertz
betainf:
  value: 111
  unit: hertz
beta0:
  value: 0.686
  unit: hertz
dValpha:
  value: 20.9
  unit: millivolt
dVbeta:
  value: -5.96
  unit: millivolt
VhalfDRK:
  value: -48.3
  unit: millivolt
dVDRK:
  value: 4.19
  unit: millivolt
mhmaxDRK:
  value: 1
  unit:
mhminDRK:
  value: 0
  unit:
deltaDRK:
  value: 0.5
  unit:

# A channel
VmhA:
  value: -55
  unit: millivolt
tauinfAgt:  # Vm>=-VmmA
  value: 5.4
  unit: millisecond
tauVtauAgt:  # Vm>=VmmA
  value: 178.4
  unit: millisecond
dVtauAgt:  # Vm>=VmmA
  value: -17.9
  unit: millivolt
VtauAgt:  # Vm>=VmmA
  value: 0
  unit: millivolt
tauinfAlt:  # Vm<VmmA
  value: 1.14
  unit: millisecond
tauVtauAlt:  # Vm<VmmA
  value: 1.62
  unit: millisecond
dVtauAlt:  # Vm<VmmA
  value: 23.1
  unit: millivolt
VtauAlt:  # Vm<VmmA
  value: 0
  unit: millivolt
dVA:
  value: 10.7
  unit: millivolt
VhalfA:
  value: -61
  unit: millivolt
mhmaxA:
  value: 1
  unit:
mhminA:
  value: 0
  unit:
deltaA:
  value: 1
  unit:
deltatauA:
  value: 1
  unit:

# A1 channel
aA1inf:
  value: 0.54
  unit:
VhalfaA1:
  value: -21.5
  unit: millivolt
dVaA1:
  value: -15.6
  unit: millivolt
tauinfA1:
  value: 74
  unit: millisecond
tauVtauA1:
  value: 395
  unit: millisecond
VtauA1:
  value: -82
  unit: millivolt
dVtauA1:
  value: 15.6
  unit: millivolt
dVA1:
  value: -3.9
  unit: millivolt
VhalfA1:
  value: -83
  unit: millivolt
mhmaxA1:
  value: 1
  unit:
mhminA1:
  value: 0
  unit:
deltaA1:
  value: 1
  unit:
deltatauA1:
  value: 2
  unit:

# A2 channel
tauinfA2:
  value: 300
  unit: millisecond
tauVtauA2:
  value: 300
  unit: millisecond
VtauA2:
  value: -82
  unit: millivolt
dVtauA2:
  value: 15.5
  unit: millivolt
dVA2:
  value: -3.9
  unit: millivolt
VhalfA2:
  value: -83
  unit: millivolt
mhmaxA2:
  value: 1
  unit:
mhminA2:
  value: 0
  unit:
deltaA2:
  value: 1
  unit:
deltatauA2:
  value: 2
  unit:

# channel reference potential
ECa:
  value: 42.5
  unit: millivolt
EK1f:
  value: -95
  unit: millivolt
EK1s:
  value: -95
  unit: millivolt
Eh:
  value: -40
  unit: millivolt
EBKS:
  value: 0
  unit: millivolt
EBKT:
  value: 0
  unit: millivolt
EDRK:
  value: 0
  unit: millivolt
EA1:
  value: 0
  unit: millivolt
EA2:
  value: 0
  unit: millivolt
EL:
  value: 0
  unit: millivolt
ET:
  value: 0
  unit: millivolt

# channel conductance or permeability
gCa1:
  value: 3.2
  unit: nanosiemens
gK1f1:
  value: 28
  unit: nanosiemens
gK1s1:
  value: 28
  unit: nanosiemens
PBKS:
  value: 0.2
  unit: picoliter/second
PBKT:
  value: 1.4
  unit: picoliter/second
PA1:
  value: 0.03
  unit: picoliter/second
PA2:
  value: 0.03
  unit: picoliter/second
PDRK:
  value: 0.064
  unit: picoliter/second
gh1:
  value: 2.2
  unit: nanosiemens
gL:
  value: 1.0
  unit: nanosiemens
PT: # permeability for transduction channels
  value: 1
  unit: micrometer**3/second
Cm:  # capacitance for soma membrane
  value: 14
  unit: picofarad
Cahbin:  # intracellular Ca2+ concentration at hair bundle
  value: 15
  unit: nanomolar
Cahbex:  # extracellular Ca2+ concentration at hair bundle
  value: 250
  unit: micromolar
Ksomain:  # intracellular K+ concentration at soma
  value: 112
  unit: millimolar
Ksomaex:  # extracellular K+ concentration at soma
  value: 2
  unit: millimolar
N:  # number of transduction channels
  value: 60
  unit:
d:  # gating swing distance [in direction of gating spring]
  value: 8.2
  unit: nanometer
dE0:  # intrinsic energy change upon opening transduction channel
  value: 65
  unit: zeptojoule
tauT0:  # time constant for opening of transduction channeling
  value: 0.8
  unit: millisecond

# Soma
Vm0: # soma membrane potential when set constant
  value: -55
  unit: millivolt

# BK channel kinetic scheme
KC10:
  value: 18.4
  unit: micromolar
KC20:
  value: 45
  unit: micromolar
KO20:
  value: 61.2
  unit: micromolar
deltaC1:
  value: 0.2
  unit:
deltaC2:
  value: 0
  unit:
deltaO2:
  value: 0.2
  unit:
kdC1:
  value: 0.3
  unit: kilohertz
kdC2:
  value: 5
  unit: kilohertz
kdO3:
  value: 0.3
  unit: kilohertz
kaO2:
  value: 1
  unit: kilohertz
kdO20:
  value: 11.3
  unit: kilohertz
dK:
  value: 0.6104
  unit:

# friction or drag coefficient
lambdaH:  # hydrodynamic drag in hair bundle, excluding channel friction
  value: 86
  unit: nanonewton*second/meter
lambdaa:  # adaptation motor drag
  value: 8.8
  unit: micronewton*second/meter

# reference position
xsp:  # stereociliary pivot
  value: 246
  unit: nanometer
xc:  # adaptation motor
  value: 12
  unit: nanometer
xes:  # extent spring
  value: 0
  unit: nanometer
rm:  # distance from adaptation motor to transduction channel
  value: 20
  unit: nanometer
rr:  # distance from reclosure element to transduction channel
  value: 10
  unit: nanometer
kar: # reclosure element association constant
  value: 2e3
  unit: kilohertz/millimolar
kdr: # reclosure element dissociation constant
  value: 35
  unit: kilohertz
kam: # association constant for adaptation motor
  value: 30
  unit: kilohertz/millimolar
kdm: # adaptation motor dissociation constant
  value: 15
  unit: kilohertz
kes: # extent spring stiffness
  value: 140
  unit: micronewton/meter
ksp: # stiffness for stereociliary pivot
  value: 190
  unit: micronewton/meter
kgs0:
  value: 2550
  unit: micronewton/meter
kgs1:
  value: 550
  unit: micronewton/meter
S0:
  value: 0
  unit: kilometer/second/newton
S1:
  value: 610
  unit: kilometer/second/newton
C0:
  value: 0.12
  unit: micrometer/second
C1:
  value: 0
  unit: micrometer/second
